--
-- PostgreSQL database dump
--

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

-- Started on 2026-01-16 16:23:22

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 16564)
-- Name: zgony; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.zgony (
    id integer NOT NULL,
    imie_nazwisko text NOT NULL,
    wiek text,
    miejsce_urodzenia text,
    data_zgonu text,
    przyczyna_zgonu text,
    inne_wazne_informacje text,
    source_file text,
    image_url text,
    parafia text
);


ALTER TABLE public.zgony OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16563)
-- Name: zgony_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.zgony_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.zgony_id_seq OWNER TO postgres;

--
-- TOC entry 5013 (class 0 OID 0)
-- Dependencies: 219
-- Name: zgony_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.zgony_id_seq OWNED BY public.zgony.id;


--
-- TOC entry 4856 (class 2604 OID 16567)
-- Name: zgony id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zgony ALTER COLUMN id SET DEFAULT nextval('public.zgony_id_seq'::regclass);


--
-- TOC entry 5007 (class 0 OID 16564)
-- Dependencies: 220
-- Data for Name: zgony; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (30, 'Jan Fogel', '33', 'Łódź', '29 grudnia 1939, godzina niewiadoma', 'brak informacji', 'Akt zgonu sporządzono 3 stycznia 1940 roku o godzinie 12:00 w kancelarii parafii Matki Boskiej Zwycięskiej w Łodzi. Zmarły był robotnikiem. Rodzice zmarłego to Wiktor Fogel i Helena z Weizmanów. Jan Fogel zamieszkiwał w Łodzi. Świadkami byli Ludwik Samitek, robotnik, zamieszkały w Łodzi, oraz Antoni Giza, robotnik, zamieszkały w Łodzi. Akt został przeczytany, przyjęty i podpisany. Urzędnik Stanu Cywilnego, Ksiądz: Władysław Gurowski. Świadkowie (podpisy): Ludwik Samitek, Antoni Giza.', 'wynik.json', '\static\parafia rzymskokatolickiej Matki Boskiej Zwycięskiej w Łodzi\1940 rok\2\22.jpg', 'Parafia rzymskokatolickiej Matki Boskiej Zwycięskiej w Łodzi');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (26, 'Jadwiga Stasiak', '17', 'Łódź', '31 grudnia 1939, godzina 3:00', 'brak informacji', 'Data sporządzenia aktu: 1 stycznia 1940, godzina 13:30. Miejsce sporządzenia aktu: Kancelaria Parafii Matki Boskiej Zwycięskiej w Łodzi. Świadkowie sporządzający akt: Marian Stasiak, robotnik, zamieszkały w Łodzi; Stanisław Rzegocki, robotnik, zamieszkały w Łodzi. Miejsce zgonu: Łódź. Stan cywilny: Panna. Rodzice: Córka Władysława Stasiaka i Bronisławy z domu Przepiórkowskich. Urzędnik Stanu Cywilnego: Władysław Gurorski. Świadkowie urzędnika: niepiśmienni.', 'wynik.json', '\static\parafia rzymskokatolickiej Matki Boskiej Zwycięskiej w Łodzi\1940 rok\1\1.png', 'Parafia rzymskokatolickiej Matki Boskiej Zwycięskiej w Łodzi');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (27, 'Ludwik Miorga', '56', 'Ładybień', '30 grudnia 1939, godzina 1:00', 'brak informacji', 'Data sporządzenia aktu: 2 stycznia 1940, godzina 11:00. Miejsce sporządzenia aktu: Kancelaria Parafii Matki Boskiej Zwycięskiej w Łodzi. Świadkowie sporządzający akt: Marianna Miorga, żona zmarłego, zamieszkała w Łodzi; Zofia Ryszkowska, robotnica, zamieszkała w Łodzi. Miejsce zgonu: Łódź. Stan cywilny: Pozostawił żonę Mariannę. Rodzice: Syn Józefa Miorgi i Zofii z domu Stach. Urzędnik Stanu Cywilnego: Władysław Gurorski. Świadkowie urzędnika: niepiśmienni.', 'wynik.json', '\static\parafia rzymskokatolickiej Matki Boskiej Zwycięskiej w Łodzi\1940 rok\1\1.png', 'Parafia rzymskokatolickiej Matki Boskiej Zwycięskiej w Łodzi');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (28, 'Marianna Madalińska', '2 miesiące 2 dni', 'Łódź', '1 stycznia 1940', 'brak informacji', 'Data rejestracji: 2 stycznia 1940, godzina 11:00. Miejsce zgonu: Łódź. Godzina zgonu: 3:00. Rodzice: Stanisław Madaliński, robotnik, i Marianna Madalińska z Janosików, zamieszkali w Łodzi. Świadkowie: Stanisław Madaliński (ojciec zmarłej), robotnik, zamieszkały w Łodzi, i Maciej Grotkowski, zamieszkały w Łodzi.', 'wynik.json', '\static\parafia rzymskokatolickiej Matki Boskiej Zwycięskiej w Łodzi\1940 rok\2\11.jpg', 'Parafia rzymskokatolickiej Matki Boskiej Zwycięskiej w Łodzi');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (29, 'Konstancja Rybińska', '75 lat', 'Częstochowa', '1 stycznia 1940', 'brak informacji', 'Data rejestracji: 2 stycznia 1940, godzina 12:00. Miejsce zgonu: Łódź. Godzina zgonu: 2:00. Rodzice: Wojciech i Marianna (nazwiska niewiadome). Świadkowie: Stanisława Pakulska, robotnik, zamieszkała w Łodzi, i Helena Wojtek, robotnica, zamieszkała w Łodzi.', 'wynik.json', '\static\parafia rzymskokatolickiej Matki Boskiej Zwycięskiej w Łodzi\1940 rok\2\11.jpg', 'Parafia rzymskokatolickiej Matki Boskiej Zwycięskiej w Łodzi');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (39, 'Kazimierz Łakomy', '36', 'Odmieska', '4 stycznia 1918, godzina 18:00', 'brak informacji', 'Akt zgonu sporządzono 5 stycznia 1940 roku o godzinie 15:00 w kancelarii parafii Matki Boskiej Anielskiej w Łodzi. Świadkowie: Bolesław Łakomy, robotnik, zamieszkały w Łodzi, oraz Bronisława Łakoma, żona zmarłego, zamieszkała w Łodzi. Zmarły zamieszkał w Łodzi. Syn Michała i Jadwigi z Brzózowskich, małżonków Łakomych. Urzędnik: Władysław Gurowski.', 'wynik.json', '\static\parafia rzymskokatolickiej Matki Boskiej Zwycięskiej w Łodzi\1940 rok\5\51.jpg', 'Parafia rzymskokatolickiej Matki Boskiej Zwycięskiej w Łodzi');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (47, 'Aniela Kurzynar', '52 lata', 'brak informacji', '02.01.1941', 'Choroba', 'Żona Tomasza Kuzniara, córka Jana Falgesa i Marianny Gilkres. Mieszkała w H. Prowiecz. Pochowana w poświęconej ziemi. Urodzona 04.06.1888.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\1\11.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (48, 'Zofia Litwin', '2 lata', 'brak informacji', '12.01.1941', 'Osłabienie', 'Córka Franciszka i Marianny Prumier. Mieszkała w H. Prowiecz. Pochowana w poświęconej ziemi. Urodzona 10.12.1941.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\1\11.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (49, 'Agata Buszcza', '62 lata', 'brak informacji', '13.01.1941', 'Zapalenie płuc', 'Żona Joannesa. Matka: M. Najder. Mieszkała w H. Prowiecz. Pochowana w poświęconej ziemi. Urodzona 13.11.1878.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\1\11.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (50, 'Jan Kurzyniar', '83 lata', 'brak informacji', '23.01.1941', 'Wyniszczenie organizmu', 'Rolnik, mąż Teresy Meyer, syn Franciszka i Teresy Hartman. Mieszkał w H. Prowiecz. Pochowany w poświęconej ziemi. Urodzony 10.05.1857.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\1\11.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (51, 'Walenty Weiber', '66 lat', 'brak informacji', '28.01.1941', 'Zapalenie', 'Rolnik, mąż Anny Glitz, córki Kacpra i Zofii Hartman. Mieszkał w H. Prowiecz. Pochowany w poświęconej ziemi. Urodzony 27.05.1875.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\1\11.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (52, 'Fryderyk Kuczaj', '56 lat', 'brak informacji', '04.02.1941', 'Gruźlica', 'Syn Stefana i Anny. Wdowiec po Juliannie Baranc. Mieszkał w H. Prowiecz. Pochowany w poświęconej ziemi. Urodzony 01.05.1884.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\1\11.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (53, 'Aniela Kuczaj', '62 lata', 'brak informacji', '07.02.1941', 'Gruźlica', 'Wdowa po Sebastianie Kurzyniar. Córka Andrzeja i Zofii Baran. Mieszkała w H. Prowiecz. Pochowana w poświęconej ziemi. Urodzona 01.03.1884.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\1\11.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (31, 'Franciszka Stasiak', '37', 'Łódź', '20. dzień bieżącego roku (1940), godzina 12:00', 'brak informacji', 'Akt zgonu sporządzono 2 stycznia 1940 roku o godzinie 12:00 w kancelarii parafii Matki Boskiej Zwycięskiej w Łodzi. Franciszka Stasiak była córką Jana i Agnieszki z Rządków Stanków (nazwisko ''Stanków'' trudne do odczytania). Była żoną Kazimierza Stasiaka. Zmarła zamieszkiwała w Łodzi. Świadkami byli Kazimierz Stasiak (wdowiec), zamieszkały w Łodzi, oraz Anastazja Dolsa (robotnica), zamieszkała w Łodzi. Akt został przeczytany, przyjęty i podpisany. Urzędnik Stanu Cywilnego, Ksiądz: Władysław Gurowski. Świadkowie (podpisy): K. Stasiak, A. Dolsa. Należy zauważyć, że data zgonu w akcie (''20. dnia bieżącego roku'') jest chronologicznie po dacie sporządzenia aktu (2 stycznia 1980), co sugeruje możliwy błąd pisarski w dokumencie (np. zamiast ''ubiegłego roku'' lub brakuje miesiąca).', 'wynik.json', '\static\parafia rzymskokatolickiej Matki Boskiej Zwycięskiej w Łodzi\1940 rok\2\22.jpg', 'Parafia rzymskokatolickiej Matki Boskiej Zwycięskiej w Łodzi');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (34, 'Pelagia Wilczyńska', '62 lata', 'Siemianowo', '2 stycznia 1940', 'brak informacji', 'Akt nr 11. Data sporządzenia aktu: 5 stycznia 1940, godz. 10:00, w kancelarii parafii Matki Boskiej Zwycięskiej w Łodzi. Zmarła w Łodzi. Rodzice: Jakub i Józefa z Przyborowskich, ostatnio z domu Rogowskich. Wdowa po Edmundzie Milewskim. Zamieszkała w Łodzi. Świadkowie: Edmund Milewski (rymarz), Stanisław Piotrowski (szkolny), obaj zamieszkali w Łodzi. Urzędnik Stanu Cywilnego, Ksiądz: Władysław Gurorski.', 'wynik.json', '\static\parafia rzymskokatolickiej Matki Boskiej Zwycięskiej w Łodzi\1940 rok\4\41.jpg', 'Parafia rzymskokatolickiej Matki Boskiej Zwycięskiej w Łodzi');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (35, 'Józef Limański', '30 lat', 'wieś Drewno, powiat Koło', '20 grudnia 1939', 'brak informacji', 'Akt nr 13. Data sporządzenia aktu: 5 stycznia 1940, godz. 11:00, w kancelarii parafii Matki Boskiej Zwycięskiej w Łodzi. Zmarł w Łodzi. Rodzice: Seweryn i Stanisława z Limańskich. Żonaty z Zofią z Paprockich. Zamieszkały w Łodzi, przynależny do gminy Koło. Świadkowie: Józef Michalski (robotnik), Franciszek Limański (robotnik), obaj zamieszkali w Łodzi. Urzędnik Stanu Cywilnego, Ksiądz: Władysław Gurorski.', 'wynik.json', '\static\parafia rzymskokatolickiej Matki Boskiej Zwycięskiej w Łodzi\1940 rok\4\41.jpg', 'Parafia rzymskokatolickiej Matki Boskiej Zwycięskiej w Łodzi');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (32, 'Jan Szymanśki', '60 lat', 'miejsce niewiadome, gmina niewiadoma', '26 grudnia 1939', 'brak informacji', 'Zgon zgłoszono 4 stycznia 1940 roku. Zmarł w Łodzi. Świadkowie zgłaszający zgon: Jan Ciemierski (zamieszkały w Łodzi) i Józef Ślązak . Syn/córka rodzin niewiadomych. Akt sporządził Urzędnik Stanu Cywilnego Ksiądz Władysław Guranski, podpisany przez świadka J. Ślązaka.', 'wynik.json', '\static\parafia rzymskokatolickiej Matki Boskiej Zwycięskiej w Łodzi\1940 rok\3\3.jpg', 'Parafia rzymskokatolickiej Matki Boskiej Zwycięskiej w Łodzi');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (33, 'Sylwester Kajetan Starzyński', '2 lata', 'miejsce niewiadome, gmina niewiadoma', '2 stycznia 1980', 'brak informacji', 'Zgon zgłoszono 8 stycznia 1980 roku. Zmarł w Łodzi. Świadkowie zgłaszający zgon: Jan Ciemierski (zamieszkały w Łodzi) i Józef Ślązak (dorożkarz, zamieszkały w Łodzi). Syn/córka rodzin niewiadomych. Akt sporządził Urzędnik Stanu Cywilnego Ksiądz Władysław Guranski, podpisany przez świadka J. Ślązaka.', 'wynik.json', '\static\parafia rzymskokatolickiej Matki Boskiej Zwycięskiej w Łodzi\1940 rok\3\3.jpg', 'Parafia rzymskokatolickiej Matki Boskiej Zwycięskiej w Łodzi');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (36, 'Stanisława Mistal', '36 lat', 'Boików, powiat Piotrkowski', '3 stycznia 1940', 'brak informacji', 'Data sporządzenia aktu: 5 stycznia 1940, godzina 11.00. Miejsce sporządzenia aktu: kancelaria parafii Matki Boskiej Anielskiej w Łodzi. Świadkowie: Józef Mistal (robotnik, zamieszkały w Łodzi), Franciszek Lemański (robotnik, zamieszkały w Łodzi). Godzina zgonu: 13.00. Miejsce zgonu: Łódź. Miejsce zamieszkania: Łódź. Rodzice: Józef i Marianna z Maślaków. Stan cywilny: żona Augusta Miszala.', 'wynik.json', '\static\parafia rzymskokatolickiej Matki Boskiej Zwycięskiej w Łodzi\1940 rok\4\42.jpg', 'Parafia rzymskokatolickiej Matki Boskiej Zwycięskiej w Łodzi');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (37, 'Janina Doliba', '15 lat', 'Łódź', '4 stycznia 1940', 'brak informacji', 'Data sporządzenia aktu: 5 stycznia 1940, godzina 15.00. Miejsce sporządzenia aktu: kancelaria parafii Matki Boskiej Anielskiej w Łodzi. Świadkowie: Stanisław Doliba (robotnik, zamieszkały w Łodzi), Zygmunt Marcinkowski (robotnik, zamieszkały w Łodzi). Godzina zgonu: 13.00. Miejsce zgonu: Łódź. Miejsce zamieszkania: Łódź. Rodzice: Jan i Antonina z Hiss Doliba.', 'wynik.json', '\static\parafia rzymskokatolickiej Matki Boskiej Zwycięskiej w Łodzi\1940 rok\4\42.jpg', 'Parafia rzymskokatolickiej Matki Boskiej Zwycięskiej w Łodzi');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (38, 'Adela Schmidt', '30', 'Łódź', '7 stycznia 1940, godzina 17:00', 'brak informacji', 'Akt zgonu sporządzono 5 stycznia 1940 roku o godzinie 15:00 w kancelarii parafii Matki Boskiej Anielskiej w Łodzi. Świadkowie: Józef Krupa, rolnik, zamieszkały w Łodzi, oraz Andrzej Aleksejew (Hintarg), mechanik, zamieszkały w Łodzi. Zmarła była wdową, zamieszkałą w Łodzi. Córka Marianny (nazwisko panieńskie nieznane). Urzędnik: Władysław Gurowski.', 'wynik.json', '\static\parafia rzymskokatolickiej Matki Boskiej Zwycięskiej w Łodzi\1940 rok\5\51.jpg', 'Parafia rzymskokatolickiej Matki Boskiej Zwycięskiej w Łodzi');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (40, 'Wilhelm Grajlich', '60', 'Łódź', '18 stycznia 1940', 'brak informacji', 'Zgłoszenie zgonu nastąpiło 19 stycznia 1940 roku o godzinie 15:00 w kancelarii parafii Matki Boskiej Imiejnskiej w Łodzi. Świadkowie pełnoletni: Helena Grajlich (żona zmarłego), zamieszkała w Łodzi; Franciszek Libisz (Inżhalto), zamieszkały w Łodzi. Zmarł o godzinie 12:00 w Łodzi. Rodzice: Wilhelm i Otylia z Kubasików, małżonkowie Grajlichowie. Żona: Helena z Libiszów. Akt ten został przeczytany, przyjęty i podpisany. Urzędnik Stanu Cywilnego, Ksiądz: Władysław Gurowski. Świadek podpisu: Helena Grajlichowa Libisz.', 'wynik.json', '\static\parafia rzymskokatolickiej Matki Boskiej Zwycięskiej w Łodzi\1940 rok\5\52.jpg', 'Parafia rzymskokatolickiej Matki Boskiej Zwycięskiej w Łodzi');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (41, 'Kazimierz Domalążek', '18', 'Łódź', '3 stycznia 1940', 'brak informacji', 'Zgłoszenie zgonu nastąpiło 8 stycznia 1940 roku o godzinie 12:00 w kancelarii parafii Matki Boskiej Imiejnskiej w Łodzi. Świadkowie pełnoletni: Stanisława Domalążek, zamieszkała w Łodzi; Józef Kasak (dworna), zamieszkały w Łodzi. Zmarł o godzinie niewiadomej w Łodzi. Rodzice: Franciszek i Stanisława z Kubasików, małżonkowie Domalążek. Akt ten został przeczytany, przyjęty i podpisany przez Nas i drugiego świadka, pierwszy niepiśmienny. Urzędnik Stanu Cywilnego, Ksiądz: Władysław Gurowski. Świadek podpisu: J. Słowirow.', 'wynik.json', '\static\parafia rzymskokatolickiej Matki Boskiej Zwycięskiej w Łodzi\1940 rok\5\52.jpg', 'Parafia rzymskokatolickiej Matki Boskiej Zwycięskiej w Łodzi');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (42, 'Jan Kramarz', '62 lata', 'brak informacji', '18.11.1940', 'Gruźlica', 'Żonaty z Józefiną Rez, córką Jakuba i Anny. Rolnik. Mieszkał w H. Prowiecz. Pochowany w poświęconej ziemi. Urodzony 01.06.1878.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\1\11.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (43, 'Andrzej Ulman', '61 lat', 'brak informacji', '21.11.1940', 'Astma', 'Rolnik, mąż Anny Krop, córki Jakuba i Marianny Kylonny. Mieszkał w H. Prowiecz. Pochowany w poświęconej ziemi. Urodzony 01.06.1879.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\1\11.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (44, 'Alfred Roraxn', '2 lata, 10 miesięcy', 'brak informacji', '26.11.1940', 'Skaza', 'Syn Antoniego i Eleonory Foy. Mieszkał w H. Prowiecz. Pochowany w poświęconej ziemi. Urodzony 14.01.1938.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\1\11.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (45, 'Zuzanna Filov', '76 lat', 'brak informacji', '12.12.1940', 'Wyniszczenie organizmu', 'Córka Andrzeja i Marii. Mieszkała w H. Prowiecz. Pochowana w poświęconej ziemi. Urodzona 14.11.1864.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\1\11.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (46, 'Walenty Pile', '56 lat', 'brak informacji', '15.12.1940', 'Astma', 'Rolnik, mąż Heliorianny Byknor, córki Józefa i Konstancji Lur. Mieszkał w H. Prowiecz. Pochowany w poświęconej ziemi. Urodzony 27.07.1884.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\1\11.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (54, 'Franciszek Kurzyniar', '60 lat', 'brak informacji', '10.02.1941', 'Zapalenie płuc', 'Rolnik, mąż Anny Tiller, syn Andrzeja i Elżbiety Rydel. Mieszkał w H. Prowiecz. Pochowany w poświęconej ziemi. Urodzony 17.07.1874.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\1\11.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (55, 'Walenty Keizer', '82 lata', 'brak informacji', '16.02.1941', 'Wyniszczenie organizmu', 'Rolnik, wdowiec po Agnieszce Kuzniar, syn Michala i Anny Jaworz. Mieszkał w H. Prowiecz. Pochowany w poświęconej ziemi. Urodzony 24.11.1858.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\1\11.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (56, 'Helena Majnar', '80 lat', 'brak informacji', '21.02.1941', 'Wyniszczenie organizmu', 'Wdowa po Andrzeju Majnar. Córka Doroty Gelleth i Doroty Rogowsky. Mieszkała w H. Prowiecz. Pochowana w poświęconej ziemi. Urodzona 18.07.1860.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\1\11.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (57, 'Aniela Bolowajder', '88 lat', 'Friedmicz', '10.03.1941', 'brak informacji', 'Wdowa po Pawle Wojtuchna. Córka Tomasza Kiczula i Anny Nysze. Mieszkała w H. Prowiecz. Pochowana w poświęconej ziemi. Urodzona w 1852.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\1\11.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (58, 'Andrzej Trojanowicz', '74 lata', 'brak informacji', '19.03.1941', 'Astma', 'Rolnik, mąż Doroty Koczun, syn Franciszka i Teresy Baran. Mieszkał w H. Prowiecz. Pochowany w poświęconej ziemi. Urodzony 03.02.1867.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\1\11.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (59, 'Klementyna Cejnar', '24 lata', 'brak informacji', '29.03.1941', 'Nerwica', 'Córka Walentyna i Marianny Reitzer. Mieszkała w H. Prowiecz. Pochowana w poświęconej ziemi. Urodzona 24.01.1917.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\1\11.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (60, 'Jan Falger', '77 lat', 'brak informacji', '18.04.1941', 'Wyniszczenie organizmu', 'Rolnik, wdowiec po Mariannie Kurzyniar, syn Antoniego i Katarzyny Koleb. Mieszkał w H. Prowiecz. Pochowany w poświęconej ziemi. Urodzony 05.05.1864.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\1\11.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (61, 'Antoni Trojanowicz', '43 lata', 'brak informacji', '24.04.1941', 'Zapalenie płuc z krwiopluciem', 'Rolnik, mąż Marianny Trojanowicz, córki Piotra i Marianny Kuzniar. Mieszkał w H. Prowiecz. Pochowany w poświęconej ziemi. Urodzony 25.05.1897.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\1\11.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (62, 'Jan Reizer', '79 lat', 'brak informacji', '29.04.1941', 'Astma', 'Rolnik, mąż Marianny Kuzniar, syn Wojciecha i Katarzyny Lobek. Mieszkał w H. Prowiecz. Pochowany w poświęconej ziemi. Urodzony 17.02.1869.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\1\11.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (76, 'Małgorzata Gondel', '49 lat', 'brak informacji', '4 stycznia 1942', 'Choroba fercm H. prov. (niejasne)', 'urodzona 6 czerwca 1862, pochowana 7 stycznia 1942, dom nr 26, katoliczka, kobieta, wdowa po niegdyś Szymonie, synu Franciszka i Marianny Reizer; ksiądz grzebiący: brak informacji o imieniu.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\2\22.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (77, 'Marianna Bartman', '41 lat', 'brak informacji', '17 stycznia 1942', 'Porphyria ominum mortis H. prov. (Porfiria, znak śmierci H. prov.)', 'pochowana 20 stycznia 1942, dom nr 119, katoliczka, kobieta, żona Antoniego rolnika, córka Andrzeja Reizer i Katarzyny Pyrzyj; ksiądz grzebiący: brak informacji o imieniu.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\2\22.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (78, 'Wawrzyniec Pele', '73 lata', 'brak informacji', '24 stycznia 1942', 'Marasmus H. prov. niker.', 'urodzony 8 stycznia 1868, pochowany 26 stycznia 1942, dom nr 166, katolik, mężczyzna, syn Andrzeja i Franciszki Bern; ksiądz grzebiący: J. Radochowicz, kooperator.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\2\22.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (79, 'Aniela Reizer', '61 lat', 'brak informacji', '31 stycznia 1942', 'Fibre zuczkie mie (niejasne, gorączka/włóknienie)', 'urodzona 5 stycznia 1878, pochowana 2 lutego 1942, dom nr 229, katoliczka, kobieta, niepełnosprawna, handlarka, córka Ignacego i Walerii Reizer; ksiądz grzebiący: Augustyn (brak informacji o imieniu).', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\2\22.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (80, 'Marianna Drecunio', '75 lat', 'brak informacji', '14 lutego 1942', 'Starość, śmierć naturalna', 'urodzona 9 stycznia 1867, pochowana 16 lutego 1942, dom nr 161, katoliczka, kobieta, wdowa po niegdyś Antonim, synu Andrzeja Teisiej i Katarzyny Pele; ksiądz grzebiący: Kapłan J. Radochowicz.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\2\22.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (81, 'Stanisława Kluz', '31 lat', 'brak informacji', '26 lutego 1942', 'Apoplexia (Udar mózgu)', 'urodzona 24 maja 1908, pochowana 28 lutego 1942, dom nr 527, katoliczka, kobieta, żona Wawrzyńca, syna Michała Pele i Marii Gilar; ksiądz grzebiący: J. Radochowicz, kooperator.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\2\22.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (82, 'Wojciech Klymus', '72 lata', 'brak informacji', '29 lutego 1942', 'Apoplexia (Udar mózgu)', 'urodzony 1 grudnia 1869, pochowany 3 marca 1942, dom nr 43, katolik, mężczyzna, wdowiec po niegdyś Teresie, córce Szymona i Heleny Klymus; ksiądz grzebiący: Kapłan J. Radochowicz.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\2\22.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (83, 'Agnieszka Klymus', '13 lat', 'brak informacji', '4 marca 1942', 'Gruźlica płuc', 'urodzona 1 lutego 1929, pochowana 6 marca 1942, dom nr 147, katoliczka, kobieta, córka Jana i Teresy Staniek; ksiądz grzebiący: Kapłan J. Radochowicz.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\2\22.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (84, 'Marianna Janiec', '70 lat', 'brak informacji', '22 marca 1942', 'Marasmus', 'urodzona 1 stycznia 1872, pochowana 24 marca 1942, dom nr 202, katoliczka, kobieta, wdowa po niegdyś Janie, synu Wojciecha i Agnieszki Wierzchowskiej; ksiądz grzebiący: Kapłan J. Radochowicz.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\2\22.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (85, 'Ewa Sztefka', '43 lata', 'brak informacji', '23 marca 1942', 'Marasmus', 'urodzona 8 stycznia 1899, pochowana 25 marca 1942, dom nr 172, katoliczka, kobieta, żona Franciszka, syna Jana i Magdaleny Sztefka; ksiądz grzebiący: Kapłan J. Radochowicz.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\2\22.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (63, 'Stanisława Kluz', '7 tygodni', 'brak informacji', '14 maja 1941', 'Kurce (lub Kruse)', 'pochowana 16 maja 1941, dom nr 583, katoliczka, kobieta, zamężna córka Stanisława; ksiądz grzebiący: Ant. May Chambres. Inne informacje dotyczące rodziców (pl. Phantaf. Inglof. conj.) niejasne.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\2\22.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (64, 'Antoni Reizer', '70 lat', 'brak informacji', '8 czerwca 1941', 'Marasmus H. prov.', 'urodzony 1 maja 1871, pochowany 10 czerwca 1941, dom nr 367, katolik, mężczyzna, rolnik, mąż Marii i Ewy Inglof; ksiądz grzebiący: brak informacji.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\2\22.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (65, 'Roman Rycz', '17 lat', 'brak informacji', '12 czerwca 1941', 'Zapalenie gardła', 'urodzony 1 października 1923, pochowany 15 czerwca 1941, dom nr 309, katolik, mężczyzna, syn Antoniego i Marii-nowej Reizer; ksiądz grzebiący: brak informacji o imieniu.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\2\22.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (66, 'Stanisław Gilar', '2 tygodnie', 'brak informacji', '17 czerwca 1941', 'Osłabienie', 'urodzony 2 czerwca 1941, pochowany 19 czerwca 1941, dom nr 410, katolik, mężczyzna, syn Stefana i Bronisławy Reizer; ksiądz grzebiący: brak informacji o imieniu.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\2\22.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (67, 'Anna Projsnier', '50 lat', 'brak informacji', '1 lipca 1941', 'Pul. glo. H. prov. (niejasne)', 'urodzona 19 stycznia 1890, pochowana 3 lipca 1941, dom nr 290, katoliczka, kobieta, żona Sebastiana rolnika, córka Sebastiana Reizer i Anny Kliruciar; ksiądz grzebiący: brak informacji o imieniu.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\2\22.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (68, 'Aniela Lenow', '78 lat', 'brak informacji', '9 lipca 1941', 'Marasmus Cruse t. H. prov. (Marnotrawstwo/wyniszczenie, choroba Cruse t. H. prov.)', 'urodzona 8 stycznia 1862, pochowana 11 lipca 1941, dom nr 191, katoliczka, kobieta, wdowa po Franciszku, synu Agnieszki Dzierzał i Katarzyny Kornial; ksiądz grzebiący: brak informacji o imieniu.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\2\22.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (69, 'Bartłomiej Nirył', '81 lat', 'brak informacji', '24 lipca 1941', 'Ills. Todtenstarre H. prov. (Niezidentyfikowana choroba, sztywność pośmiertna H. prov.)', 'urodzony 20 sierpnia 1859, pochowany 27 lipca 1941, dom nr 268, katolik, mężczyzna, robotnik, mąż Anny Herzogowicz, poprzednio Simot; ksiądz grzebiący: brak informacji o imieniu.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\2\22.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (70, 'Aniela Bernadetta', '87 lat', 'brak informacji', '19 sierpnia 1941', 'Atta todzmiczny Provis (niejasne, atak, prowincjonalne)', 'urodzona 1 stycznia 1854, pochowana 21 sierpnia 1941, dom nr 398, katoliczka, kobieta, wdowa po niegdyś Józefie rolniku, synu Wojciecha Norwy i Moniki Nirył; ksiądz grzebiący: brak informacji o imieniu.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\2\22.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (71, 'Aniela Lobek', '53 lata', 'brak informacji', '16 sierpnia 1941', 'Wrzód żołądka', 'urodzona 1 lutego 1888, pochowana 18 sierpnia 1941, dom nr 425, katoliczka, kobieta, żona Józefa mieszczanina, córka Ignacego i Ewy Golarz; ksiądz grzebiący: brak informacji o imieniu.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\2\22.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (72, 'Jan Wolny', '4 lata', 'brak informacji', '13 września 1941', 'Marasmus', 'urodzony 1 lutego 1937, pochowany 15 września 1941, dom nr 172, katolik, mężczyzna, syn Franciszka i Ewy Sztefka; ksiądz grzebiący: brak informacji o imieniu.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\2\22.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (73, 'Maria Wolny', '38 lat', 'brak informacji', '22 września 1941', 'Gruźlica płuc', 'urodzona 1 stycznia 1903, pochowana 24 września 1941, dom nr 279, katoliczka, kobieta, żona Jana, córka Józefa i Anny Piechoczki; ksiądz grzebiący: brak informacji o imieniu.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\2\22.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (74, 'Bolesław Dworczyk', '1 rok', 'brak informacji', '27 września 1941', 'Niewydolność serca', 'urodzony 1 stycznia 1940, pochowany 29 września 1941, dom nr 11, katolik, mężczyzna, syn Jana i Agnieszki Klara; ksiądz grzebiący: brak informacji o imieniu.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\2\22.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (75, 'Józef Reizer', '84 lata', 'brak informacji', '30 września 1941', 'Marasmus tod. H. prov. (wyniszczenie, śmierć H. prov.)', 'urodzony 16 lutego 1857, pochowany 1 października 1941, dom nr 294, katolik, mężczyzna, rolnik, wdowiec po niegdyś Justynie Babiore, syn Wojciecha i Katarzyny Sobek; ksiądz grzebiący: Władysław Morawiecki, proboszcz.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\2\22.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (86, 'Jan Konieczny', '81 lat', 'brak informacji', '29 kwietnia 1942', 'Niewydolność serca', 'urodzony 1 stycznia 1861, pochowany 1 maja 1942, dom nr 254, katolik, mężczyzna, mieszczanin, wdowiec po niegdyś Franciszce, córce Jana i Marianny Konieczny; ksiądz grzebiący: Kapłan J. Radochowicz.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\2\22.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (89, 'Wincenty Byttner', '7 lat', 'brak informacji', '6 lipca 1942', 'ropotwórczy (posocznica)', 'Syn Jana i Katarzyny Byttner. Katolik. Mężczyzna. Pogrzebany przez brak informacji.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\3\33.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (87, 'Marianna trojnar', '29 lat', 'brak informacji', '19 marca 1942', 'neurastenia', 'Żona Ignacego, rolnika. Córka Józefa Hilarego i Heleny Ruempoy. Numer domu: 388. Urodzona 1 lipca 1913. Katoliczka. Kobieta. Pogrzebana przez ks. J. Radochowskiego, wikarego.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\3\33.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (88, 'Dorota Bomm', '55 lat (przybliżony, wyliczony)', 'brak informacji', '10 maja 1942', 'ropne zapalenie opon mózgowych', 'Żona Jana. Córka Tomasza i Rozalii z d. Bartman. Numer domu: 311. Urodzona 25 listopada 1887. Katoliczka. Kobieta. Pogrzebana przez ks. J. Radochowskiego, wikarego.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\3\33.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (90, 'Grzegorz (Jerzy) Dymitrzyk', '38 lat', 'brak informacji', '14 lipca 1942', 'zapalenie mózgu', 'Syn Teofila i Marianny Dymitrzyk. Urodzony 10 października 1904. Katolik. Mężczyzna. Pogrzebany przez brak informacji.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\3\33.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (91, 'Tomasz Przela', '53 lata (przybliżony, wyliczony)', 'brak informacji', '22 lipca 1942', 'kamica żółciowa', 'Mąż Anny Przela. Syn Kazimierza i Agaty Przela. Numer domu: 312. Urodzony 14 grudnia 1889. Katolik. Mężczyzna. Pogrzebany przez ks. J. Radochowskiego, wikarego.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\3\33.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (92, 'Stanisław Byttner', '1 rok 6 miesięcy', 'brak informacji', '2 sierpnia 1942', 'dyzenteria', 'Syn Jana i Ireny Byttner. Numer domu: 70. Urodzony 23 października 1941. Katolik. Mężczyzna. Pogrzebany przez ks. J. Radochowskiego, wikarego lokalnego.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\3\33.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (93, 'Walenty Szpunar', '62 lata (przybliżony, wyliczony)', 'brak informacji', '10 sierpnia 1942', 'rak', 'Rolnik. Mąż Katarzyny Szpunar. Numer domu: 264. Urodzony 29 grudnia 1880. Katolik. Mężczyzna. Pogrzebany przez ks. Wojciecha Koniarza.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\3\33.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (94, 'Karolina Kuźniak', '78 lat', 'brak informacji', '14 sierpnia 1942', 'starość', 'Żona Grzegorza Kuźniaka. Córka Marcina Koniarskiego. Numer domu: 212. Urodzona 11 września 1864. Katoliczka. Kobieta. Pogrzebana przez ks. J. Radochowskiego, wikarego.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\3\33.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (95, 'Wojciech Orte', '1 miesiąc 12 dni', 'brak informacji', '22 sierpnia 1942', 'słabość wrodzona', 'Syn Bolesława i Anny Marii z d. Siarkiewicz. Urodzony 10 lipca 1942. Katolik. Mężczyzna. Pogrzebany przez ks. J. Radochowskiego, wikarego.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\3\33.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (96, 'Zofia Hwiwir', '57 lat (przybliżony, wyliczony)', 'brak informacji', '18 września 1942', 'surowicze zapalenie opon mózgowych', 'Wdowa po Adalbercie Kuźmirze. Córka Walentego Hianowskiego i Marianny. Numer domu: 221. Urodzona 9 stycznia 1885. Katoliczka. Kobieta. Pogrzebana przez ks. A. Radochowskiego J.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\3\33.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (97, 'Zofia Błajsz', '4 miesiące 3 dni', 'brak informacji', '14 września 1942', 'przewlekły suchy nieżyt nosa', 'Córka Jana i Heleny Trzylar. Numer domu: 182. Urodzona 11 maja 1942. Katoliczka. Kobieta. Pogrzebana przez brak informacji.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\3\33.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (98, 'Stefania Hwinko', 'brak informacji', 'brak informacji', '20 września 1942', 'brak informacji', 'Katoliczka. Kobieta. Pogrzebana przez brak informacji.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\3\33.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (99, 'Grzegorz Kuźnir', '80 lat (przybliżony, wyliczony)', 'brak informacji', '25 września 1942', 'surowicze zapalenie opon mózgowych', 'Wdowiec. Syn Józefa i Katarzyny Dymytryk. Numer domu: 57. Urodzony 8 marca 1862. Katolik. Mężczyzna. Pogrzebany przez brak informacji.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\3\33.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (100, 'Zofia Izebęk', '76 lat (przybliżony, wyliczony)', 'brak informacji', '22 września 1942', 'surowicze zapalenie opon mózgowych', 'Żona Andrzeja, rolnika. Córka Walentego i Katarzyny Trzyjar. Numer domu: 314. Urodzona 11 grudnia 1866. Katoliczka. Kobieta. Pogrzebana przez brak informacji.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\3\33.png', 'Parafia rzymskokatolickiej Albigowa');
INSERT INTO public.zgony (id, imie_nazwisko, wiek, miejsce_urodzenia, data_zgonu, przyczyna_zgonu, inne_wazne_informacje, source_file, image_url, parafia) VALUES (101, 'Edmund Horbecki', '21 lat (przybliżony, wyliczony)', 'Strzyżów', '30 września 1942', 'zapalenie mózgu', 'Robotnik. Syn Andrzeja i Zofii. Numer domu: 63. Urodzony 29 maja 1921. Katolik. Mężczyzna. Pogrzebany przez brak informacji.', 'wynik.json', '\static\parafia rzymskokatolickiej Albigowa\1940-45\3\33.png', 'Parafia rzymskokatolickiej Albigowa');


--
-- TOC entry 5014 (class 0 OID 0)
-- Dependencies: 219
-- Name: zgony_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.zgony_id_seq', 101, true);


--
-- TOC entry 4858 (class 2606 OID 16573)
-- Name: zgony zgony_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zgony
    ADD CONSTRAINT zgony_pkey PRIMARY KEY (id);


-- Completed on 2026-01-16 16:23:23

--
-- PostgreSQL database dump complete
--


